/**
 * SIWIAT Out App - JSON
 * This is a description for the [Out App \"JSON\"](http://siwiat.com/app/view/?appname=json) for the SIWIAT App-Box.  This specification complies with the JSON App version 1.0.3 (Oct 2016)  [Learn more about SIWIAT](http://siwiat.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/GetValuesResponse'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'), require('../model/GetValuesResponse'));
  } else {
    // Browser globals (root is window)
    if (!root.SiwiatOutAppJson) {
      root.SiwiatOutAppJson = {};
    }
    root.SiwiatOutAppJson.ValuesApi = factory(root.SiwiatOutAppJson.ApiClient, root.SiwiatOutAppJson.GetValuesResponse);
  }
}(this, function(ApiClient, GetValuesResponse) {
  'use strict';

  /**
   * Values service.
   * @module api/ValuesApi
   * @version 1.0.0
   */

  /**
   * Constructs a new ValuesApi. 
   * @alias module:api/ValuesApi
   * @class
   * @param {module:ApiClient} apiClient Optional API client implementation to use,
   * default to {@link module:ApiClient#instance} if unspecified.
   */
  var exports = function(apiClient) {
    this.apiClient = apiClient || ApiClient.instance;


    /**
     * Callback function to receive the result of the getValuesResponse operation.
     * @callback module:api/ValuesApi~getValuesResponseCallback
     * @param {String} error Error message, if any.
     * @param {module:model/GetValuesResponse} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get channel values
     * Get channel values by the {valueid}
     * @param {String} valueids The value id of a channel
     * @param {module:api/ValuesApi~getValuesResponseCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/GetValuesResponse}
     */
    this.getValuesResponse = function(valueids, callback) {
      var postBody = null;

      // verify the required parameter 'valueids' is set
      if (valueids == undefined || valueids == null) {
        throw new Error("Missing the required parameter 'valueids' when calling getValuesResponse");
      }


      var pathParams = {
      };
      var queryParams = {
        'valueids': valueids
      };
      var headerParams = {
      };
      var formParams = {
      };

      var authNames = [];
      var contentTypes = ['application/json'];
      var accepts = ['application/json'];
      var returnType = GetValuesResponse;

      return this.apiClient.callApi(
        '/getvalues', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }
  };

  return exports;
}));
