/**
 * SIWIAT Out App - JSON
 * This is a description for the [Out App \"JSON\"](http://siwiat.com/app/view/?appname=json) for the SIWIAT App-Box.  This specification complies with the JSON App version 1.0.3 (Oct 2016)  [Learn more about SIWIAT](http://siwiat.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SiwiatOutAppJson);
  }
}(this, function(expect, SiwiatOutAppJson) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SiwiatOutAppJson.Channel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('Channel', function() {
    it('should create an instance of Channel', function() {
      // uncomment below and update the code to test Channel
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be.a(SiwiatOutAppJson.Channel);
    });

    it('should have the property channelmetaid (base name: "channelmetaid")', function() {
      // uncomment below and update the code to test the property channelmetaid
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property valueid (base name: "valueid")', function() {
      // uncomment below and update the code to test the property valueid
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property app (base name: "app")', function() {
      // uncomment below and update the code to test the property app
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property deviceid (base name: "deviceid")', function() {
      // uncomment below and update the code to test the property deviceid
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property devicecaption (base name: "devicecaption")', function() {
      // uncomment below and update the code to test the property devicecaption
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property channelno (base name: "channelno")', function() {
      // uncomment below and update the code to test the property channelno
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property interval (base name: "interval")', function() {
      // uncomment below and update the code to test the property interval
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property caption (base name: "caption")', function() {
      // uncomment below and update the code to test the property caption
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property measurementname (base name: "measurementname")', function() {
      // uncomment below and update the code to test the property measurementname
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property unitname (base name: "unitname")', function() {
      // uncomment below and update the code to test the property unitname
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property valuemin (base name: "valuemin")', function() {
      // uncomment below and update the code to test the property valuemin
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

    it('should have the property valuemax (base name: "valuemax")', function() {
      // uncomment below and update the code to test the property valuemax
      //var instane = new SiwiatOutAppJson.Channel();
      //expect(instance).to.be();
    });

  });

}));
