/**
 * SIWIAT Out App - JSON
 * This is a description for the [Out App \"JSON\"](http://siwiat.com/app/view/?appname=json) for the SIWIAT App-Box.  This specification complies with the JSON App version 1.0.3 (Oct 2016)  [Learn more about SIWIAT](http://siwiat.com) 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

(function(factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient', 'model/Channel', 'model/GetChannelsResponse', 'model/GetValuesResponse', 'model/Value', 'api/ChannelsApi', 'api/ValuesApi'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('./ApiClient'), require('./model/Channel'), require('./model/GetChannelsResponse'), require('./model/GetValuesResponse'), require('./model/Value'), require('./api/ChannelsApi'), require('./api/ValuesApi'));
  }
}(function(ApiClient, Channel, GetChannelsResponse, GetValuesResponse, Value, ChannelsApi, ValuesApi) {
  'use strict';

  /**
   * This_is_a_description_for_the__Out_App_JSON_httpsiwiat_comappviewappnamejson_for_the_SIWIAT_App_Box_This_specification_complies_with_the_JSON_App_version_1_0_3__Oct_2016_Learn_more_about_SIWIAT_httpsiwiat_com.<br>
   * The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
   * <p>
   * An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
   * <pre>
   * var SiwiatOutAppJson = require('index'); // See note below*.
   * var xxxSvc = new SiwiatOutAppJson.XxxApi(); // Allocate the API class we're going to use.
   * var yyyModel = new SiwiatOutAppJson.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
   * and put the application logic within the callback function.</em>
   * </p>
   * <p>
   * A non-AMD browser application (discouraged) might do something like this:
   * <pre>
   * var xxxSvc = new SiwiatOutAppJson.XxxApi(); // Allocate the API class we're going to use.
   * var yyy = new SiwiatOutAppJson.Yyy(); // Construct a model instance.
   * yyyModel.someProperty = 'someValue';
   * ...
   * var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
   * ...
   * </pre>
   * </p>
   * @module index
   * @version 1.0.0
   */
  var exports = {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient: ApiClient,
    /**
     * The Channel model constructor.
     * @property {module:model/Channel}
     */
    Channel: Channel,
    /**
     * The GetChannelsResponse model constructor.
     * @property {module:model/GetChannelsResponse}
     */
    GetChannelsResponse: GetChannelsResponse,
    /**
     * The GetValuesResponse model constructor.
     * @property {module:model/GetValuesResponse}
     */
    GetValuesResponse: GetValuesResponse,
    /**
     * The Value model constructor.
     * @property {module:model/Value}
     */
    Value: Value,
    /**
     * The ChannelsApi service constructor.
     * @property {module:api/ChannelsApi}
     */
    ChannelsApi: ChannelsApi,
    /**
     * The ValuesApi service constructor.
     * @property {module:api/ValuesApi}
     */
    ValuesApi: ValuesApi
  };

  return exports;
}));
